name: deaktiviertes Script Build Windows EXE (Optimized for Antivirus)

on:
  push:
   # branches: [ main ]
  pull_request:
   # branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pyinstaller ezdxf

      - name: Build EXE without UPX Compression
        run: |
          pyinstaller --onefile --clean --strip dxfLength.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dxfLength-windows
          path: dist/dxfLength.exe
